// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xquudzbxonbvodprxvfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxdXVkemJ4b25idm9kcHJ4dmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NzMxNTUsImV4cCI6MjA4NTU0OTE1NX0.M8P1K_N-9EHTfOFkVsENiZzTmkw7wqVc6mfDd4oa-hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});